### PR TITLE
Using stock FMDB and SQLCipher (with FTS)

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Comment by bhariharan** [comment]
:+1:

**Comment by kchitalia** [comment]
:+1:

**Comment by khawkins** [comment]
Have we tested this?  Stock FMDB depends on sqlite3.  Are there going to be symbol clashes when we effectively go against both?

**Comment by khawkins** [comment]
Also, FMDB is the spec that has to compile against `DSQLITE_HAS_CODEC`.  That was the whole reason for splitting it out: the default FMDB spec does not set it.

**Comment by khawkins** [comment]
My recommendation would be to keep our FMDB spec, but swap out the vendored library for a dependency on `SQLCipher/fts`.

**Comment by wmathurin** [comment]
You are probably right, I'll make the change.

**Comment by khawkins** [comment]
Another question I have with regards to re-establishing our dependency on the SQLCipher spec: is there reason to have renewed faith that the spec won't simply fall into disrepair again?  There's an argument for keeping our own version of SQLCipher, so that we can keep it maintained.

**Comment by khawkins** [comment]
But I suppose we can (re-)cross that bridge when we get to it.

**Comment by wmathurin** [comment]
Switching one way or the other is easy.
I suggest we don't call our subspec fmdb so that one doesn't end up picking up the stock fmdb by having the sources in the wrong order.
How about SalesforceFMDB?

**Comment by khawkins** [comment]
The problem with renaming the spec is that it filters all the way through to the header paths, with implications on non-modular header imports et al.  So far I haven't been able to find the way to effectively "rename" the target internally to differentiate it from the named spec.

**Comment by wmathurin** [comment]
Ah ok, I'll keep the name then and make sure to have our specs repo source first in all the templates.

**Comment by wmathurin** [comment]
How does it look now?

**Comment by khawkins** [comment]
Looks good.  I *do* like the idea of renaming the spec, if we can find a way.  I wonder if `spec.module_name` ([here](https://guides.cocoapods.org/syntax/podspec.html#tab_module_name)) would do the trick in the pod spec?

**Comment by wmathurin** [comment]
I think it should (https://guides.cocoapods.org/syntax/podspec.html#module_name)

**Comment by wmathurin** [comment]
I can't get it to work as SalesforceFMDB with module_name - so I'll leave it as FMDB for now

**Comment by khawkins** [comment]
Sounds good.  We can look into further. :+1:

**Pull request merged**
